# Generated by Django 3.2.5 on 2021-09-15 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_employee_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='birthday',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='position',
            field=models.CharField(choices=[('Страховой агент', 'Страховой агент'), ('Консультант', 'Консультант'), ('Охранник', 'Охранник'), ('Админ', 'Админ')], max_length=200, null=True),
        ),
    ]
