# Generated by Django 3.2.5 on 2021-09-15 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20210915_1840'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='date_created',
        ),
    ]
