# Generated by Django 3.2.5 on 2021-09-12 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policy_num', models.CharField(max_length=20)),
                ('full_name', models.CharField(max_length=100)),
                ('birthday_date', models.DateField()),
                ('start_policy_date', models.DateField()),
                ('end_policy_date', models.DateField()),
                ('company', models.CharField(max_length=100)),
                ('mail', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=20)),
            ],
        ),
    ]
