# Generated by Django 3.2.5 on 2021-09-15 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_auto_20210914_1506'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='mail',
            new_name='email',
        ),
    ]
