# Generated by Django 3.2.5 on 2021-09-15 22:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_rename_mail_client_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='end_policy_date',
            new_name='policy_end_date',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='start_policy_date',
            new_name='policy_start_date',
        ),
    ]
