# Generated by Django 3.2.5 on 2021-09-16 12:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_remove_employee_date_created'),
        ('clients', '0005_auto_20210915_2247'),
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_case', models.IntegerField(null=True)),
                ('case_start_date', models.DateField(auto_now_add=True, null=True)),
                ('case_end_date', models.DateField(null=True)),
                ('status', models.BooleanField(null=True)),
                ('notes', models.TextField(null=True)),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='clients.client')),
                ('coordinator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.employee')),
            ],
        ),
    ]
