# Generated by Django 3.2.5 on 2021-10-28 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0006_case'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='case_start_date',
            field=models.DateField(null=True),
        ),
    ]
